id: 4d053774f5df483fae04cb029a254174
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_212-The_Sutra_on_Dependent_Arising-v1
  language: bo
  author: ''
  volume: {}
